BEGIN;

DELETE FROM excuse_votes;
DELETE FROM excuses;

INSERT INTO excuses (text, category, is_active) VALUES ('Leg day.', 'physical', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Back''s tight.', 'physical', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Two hours of sleep.', 'physical', true);
INSERT INTO excuses (text, category, is_active) VALUES ('I slipped.', 'physical', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Jacket''s too tight.', 'physical', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Too bloated to rotate.', 'physical', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Lumbago.', 'physical', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Legs are dead.', 'physical', true);
INSERT INTO excuses (text, category, is_active) VALUES ('New knees.', 'physical', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Can''t feel anything today.', 'physical', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Aches and pains.', 'physical', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Foot slipped.', 'physical', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Too much coffee, hands shaky.', 'physical', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Tee time was too early.', 'physical', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Bad back.', 'physical', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Tore my Achilles.', 'physical', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Glutes aren''t firing.', 'physical', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Gym this morning.', 'physical', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Working on something new.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Overthinking the putt.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('I play better alone.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('No warm up.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('You warmed up, I didn''t.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('3-footers kill me.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Still thinking about last year''s triple.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Left my swing at home.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Cart path only threw me off.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Was striping it at the range.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Haven''t hit the range in weeks.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Worst round in five years.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Just once, my normal game.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Didn''t want to fly the green.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Pin''s tucked too tight.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Never charge a downhill putt.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('30-footers? Easy. 3-footers? Done.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Practice green? Money. Course? Gone.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Negative thoughts.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Lost concentration.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('New course.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Visualized the wrong shot.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Should''ve watched a tips video.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Never taken a lesson.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Haven''t played in 3 years.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Didn''t play as a kid.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Over-practiced.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Wrong club.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Need a ball that goes straight.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Defective ball.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Need new clubs.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('150 marker''s wrong.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Glove''s too tight.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Wrong ball.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Cracked tee.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Love these new clubs!', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Hate these new clubs!', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Ball''s cracked.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('I hate that driver.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Obviously the wrong club.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Yardage must be wrong.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Defective ball, statistically.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Kids'' clubs all week.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Grooves are worn out.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Between clubs. Picked wrong.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Sand wedge has a mind of its own.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Putter face was open.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Plumb bob lied.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Changed putters before the round.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Trying new balls.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Rangefinder lied.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Breaking in new grips.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Lucky ball''s in the water.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Should''ve clubbed up.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Testing a new shaft.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('App gave wrong distance.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Worn-out shoe soles.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Putter''s twisted.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Ball''s ruined.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('It''s my loft.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Forgot to charge my clubs.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('GPS said 150. Rangefinder said 145. Hit 200.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Barometric pressure.', 'weather', true);
INSERT INTO excuses (text, category, is_active) VALUES ('The glare.', 'weather', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Too hot.', 'weather', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Too cold.', 'weather', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Could barely swing, too cold.', 'weather', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Wind picked up mid-swing.', 'weather', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Sun in my eyes.', 'weather', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Wind changed.', 'weather', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Too sunny.', 'weather', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Wind got it.', 'weather', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Wind took it.', 'weather', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Sudden gust, did you feel that?', 'weather', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Hands too sweaty.', 'weather', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Ball feels like a rock.', 'weather', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Can''t play in this heat.', 'weather', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Wind didn''t cooperate.', 'weather', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Wind carried it over.', 'weather', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Frickin'' wind!', 'weather', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Course was too wet.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Uneven greens.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Grass was wrong length.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Sprinkler head.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Bad lie.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Rolled too far.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Didn''t roll at all.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Putt broke more than expected.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Greens are too fast.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Greens are too bumpy.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Hate this bunker sand.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Sand was too fluffy.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Greens aren''t watered enough.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Too much dew.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Fringe was against me.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Ball sitting down in the rough.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Stimp''s at least 14.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Grain went the other way.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Spike marks.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Cruel pin placement.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('That divot wasn''t there yesterday.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Mud ball.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Ground too soft.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Lie was worse than it looked.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Someone talked in my backswing.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Someone hollered.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Heard a glove come off.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Group ahead is too slow.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Squirrel stared at me.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Standing too close.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Someone coughed.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Bug in my face.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Phone''s dead, can''t focus.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Cart whiplash.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Got rushed.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Stop laughing.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Too much waiting.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Group behind is too fast.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Airplane flew over.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Bird dive-bombed me.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Someone smacking gum.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Don''t talk to my ball.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Groundhog.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Somebody moved.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Shadow crossed my line.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Saw my shadow.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Watch buzzed.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Marshal was staring.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Partner breathed too loud.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('There was a bee!', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Phone vibrated.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Did you hear that???', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Rolled back into the bunker.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Unlucky bounce.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Bounces weren''t going my way.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Was this OB last week?', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Who planted that tree?', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Who puts a bunker there?', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Bunker lip was way higher.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Golf Gods hate me.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Ball mark changed the break.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Ball aimed for the water.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Found water with no hazard.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Course swallowed it.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Trees jumped out.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Hole rejected me.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Bad luck.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Perfect if that tree wasn''t there.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Ball had other plans.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('New swing, bedding it in.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Inconsistency is my trademark.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Fly fishing or golfing?', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Lifted my head.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Swinging like a football bat.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Failed to snap load.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Tee too low.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Tee too high.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Skulled the chip.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Bump-and-run didn''t bump or run.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Decelerated.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Didn''t commit.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Looked up.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Arms ahead of hips.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Weird hitch.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Inside out.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Hit behind it.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Face was open.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Hosel rocket.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Heeled it.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Right line, wrong speed.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Right speed, wrong line.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Left my draws at home.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Good bogey hole.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Not losing my Tour card.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('I usually slice, why is it straight?', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Great at mini golf.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Hole''s not regulation.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Gonna be one heck of a par.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Thinking about going pro.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Too strong for this game.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Lie was too perfect.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Green read it differently.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Hole moved.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Aggressive green reading.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Nice lag.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('That''s not OB, alternative fairway.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('I know where it is. Can''t get to it.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Scenic route to the green.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('It''s a power fade.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('At least I go again.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Different strategy.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Saving good shots for the back nine.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Prefer the rough.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Ball just disagreed.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Strategic fairway search.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Right shot, wrong hole.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Problem happened after impact.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Better angle from here.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Ball usually listens.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Playing it like the architect intended.', 'course', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Paid for the whole course.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Got hit by a car.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Underwear riding up.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Snake might be in there.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Need a manicure first.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Standing too close to the course.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Wind in my eyes.', 'weather', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Pick up for a double?', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Told Beyoncé not to text me.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Earth''s rotation.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Left-handed ball.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Born insufficiently talented.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Stepped on the rake.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Four putts build character.', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Yelled fore, ball didn''t listen.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('One under a tree, bush, and water.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Don''t have a caddie.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Mostly moved earth.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('That''s why I ate that.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Mulligan on each hole.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('What game is this?', 'mental', true);
INSERT INTO excuses (text, category, is_active) VALUES ('I blinked.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Pulled a muscle reaching for scorecard.', 'physical', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Blamed the pants.', 'equipment', true);
INSERT INTO excuses (text, category, is_active) VALUES ('LOFT — lack of talent.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Need the bathroom.', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Spacetime bends left around my driver.', 'bad_luck', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Better if I was better at golf.', 'skill', true);
INSERT INTO excuses (text, category, is_active) VALUES ('I was in the pool!', 'distraction', true);
INSERT INTO excuses (text, category, is_active) VALUES ('Earth rotated under it.', 'bad_luck', true);

COMMIT;
