export const EXCUSES = [
  "It was leg day today.",
  "Barometric pressure must be dropping today.",
  "My wife gave me a list of honey do's before I could get out to play.",
  "Back is tight, can't swing my normal swing.",
  "I need some new clubs.",
  "I had some negative thoughts before I hit that.",
  "It's a good bogey hole anyway.",
  "Just can't feel anything today.",
  "No sleep.",
  "That guy three holes over was talking during my backswing.",
  "Grabbed the wrong club.",
  "Someone hollered three holes over.",
  "The glare got me.",
  "You're standing too close (even though you're nowhere near).",
  "I heard you taking off your glove in my backswing.",
  "My golf coach has me working on something new.",
  "I'm trying a new swing, still bedding it in.",
  "Did you see what I ate? That's why.",
  "The people in front are so slow, gets me out of my rhythm.",
  "I slipped. (One per round when it's soggy.)",
  "My underwear keeps riding up.",
  "This jacket is too restrictive.",
  "That squirrel was looking at me during my backswing.",
  "It was too hot, I got dehydrated and lost my focus.",
  "It was too cold, the ball wasn't going anywhere.",
  "I was so cold I could hardly swing the club.",
  "The wind picked up right when I was over the ball.",
  "I'm still searching for a ball that goes straight.",
  "With my defective balls, a perfect shot ends up in the woods for no reason.",
  "My clubs are all mismatched and old, I'd play better with new ones.",
  "The course was so wet nothing was rolling.",
  "Uneven greens, I couldn't trust a single putt.",
  "A squirrel was chewing a nut in a tree two fairways away, threw me off.",
  "Some days you're not free of aches and pains, today was one of them.",
  "Perfect shot, then it rolled back into the bunker, some days you can't buy a shot.",
  "Great drive, then an unlucky bounce and a 90 degree turn into the hazard.",
  "The bounces just weren't going my way today.",
  "Inconsistent swing is the trademark of my game.",
  "I'm not sure if I was fly fishing or golfing out there.",
  "I looked like I got kicked by a horse and then stung by a bee during my swing.",
  "I stood over the putt thinking \"What am I lying?\" instead of making the putt.",
  "I score lower when I play alone, no distractions today.",
  "I just lost concentration on that one.",
  "I flew in five minutes before tee time, no warm up.",
  "You had an hour of range and putting, I had five minutes. Life isn't fair.",
  "It's not like I'm going to lose my Tour card, but still.",
  "I hit my 150 yard club and came up 20 yards short, the 150 marker's in the wrong place.",
  "The maintenance staff put that marker in the wrong spot, not my fault.",
  "The sun was in my eyes.",
  "Someone coughed during my backswing.",
  "The grass was the wrong length.",
  "My glove was too tight.",
  "A bug flew in my face.",
  "The wind changed mid swing.",
  "Wrong ball, I thought it was mine.",
  "Cart path only, threw off my routine.",
  "Was this out of bounds last week?",
  "I had my mulligan on each hole.",
  "My tee had a crack in it.",
  "What game am I playing?",
  "I putted great at miniature golf yesterday.",
  "I can't focus, my cell phone is dead.",
  "I felt whiplash when you started the cart.",
  "I just love these new clubs!",
  "Those 3 footers throw me off.",
  "That darn thing got in my way.",
  "My feet hurt from too much discount shopping.",
  "Why am I hitting straight? (I usually slice.)",
  "I had my tee too low.",
  "I had my tee too high.",
  "I'm afraid a snake might be in there!",
  "I can't forget that triple bogey from last year.",
  "I hate these new clubs!",
  "It's too darn sunny out here.",
  "I play much better after a manicure.",
  "That hole isn't regulation size!",
  "My instructor said my biggest problem was standing too close… to the golf course.",
  "This is gonna be one heck of a par.",
  "Wind got ahold of that one. (Even when it's dead calm.)",
  "The wind was in my eyes.",
  "At least I get to go again.",
  "Everyone has a different strategy.",
  "Thinking about going pro, what do you guys think?",
  "Ball must be cracked.",
  "Can I pick up for a double from there?",
  "Quit hitting the ball, instead swing the club!",
  "I told Beyoncé to not text me during my backswing!",
  "Just trying to see how quickly I can match the course record.",
  "Didn't account for the earth's rotation!",
  "I think that was a left handed ball.",
  "Forgot my swing at home.",
  "A noise from the gallery when I was taking my swing.",
  "My dog wouldn't roll in that one.",
  "Lifted my head, wins every time.",
  "I'm too strong for this game.",
  "Tough break, I had a bad lie.",
  "The person two holes behind me rushed my shot, hit it out of bounds twice.",
  "I've been using the kids' clubs in the backyard all week, threw off my swing.",
  "Wind took it. (Shanked 50 yards left in a 2 mph breeze.)",
  "That was obviously the wrong club. (It was a putter.)",
  "I'm out here trying to perform miracles.",
  "Something made a noise while I was swinging, a car, a bird, a guy in a cart on the other hole.",
  "A sudden, unexpected gust of wind, did you feel that? Where did that come from?",
  "I knew I shouldn't have hit that driver. I hate that club.",
  "My wife thinks I'm out here having fun.",
  "Who had to plant a tree right there?",
  "I hit it short, the yardage on this hole must be wrong.",
  "I hit it long, the yardage on this hole must be wrong.",
  "That putt broke way more than I expected. These greens are way too fast.",
  "These greens are way too bumpy. That should have gone in.",
  "Will you stop laughing? I can't concentrate.",
  "That shot rolled too far. Don't they water the fairways?",
  "That shot didn't roll at all. These fairways are too soft.",
  "The sun is too hot, my hands are sweaty and I can't hold the club.",
  "It's too cold, the club feels stiff and the ball feels like a rock.",
  "The group in front is too slow, all that waiting throws my game off.",
  "The group behind is too fast, them waiting on us throws my game off.",
  "Way too much bad luck today. Can't wait to try again tomorrow.",
  "Airplanes and helicopters.",
  "Birds.",
  "Someone chewing gum.",
  "People celebrating on a hole two fairways over.",
  "Don't speak to my ball, you're making it go the wrong way.",
  "I swear the Golf Gods are real and they hate me.",
  "I ate too much before the round, I'm bloated. (Or: I didn't eat enough, no energy.)",
  "It's unnatural out here. (Sun, conditions, everything.)",
  "That groundhog threw me off.",
  "My lumbago is acting up.",
  "I was hitting them so well at the range yesterday.",
  "I've been stuck in the office too much to hit the range.",
  "I've played too much golf this week, the legs are dead.",
  "I hate the sand in these bunkers!",
  "Someone was narrating in my backswing.",
  "My foot slipped.",
  "Somebody moved in my backswing.",
  "I saw my shadow.",
  "The wind didn't take my ball like it was supposed to.",
  "I swear, this is the worst round I've played in five years.",
  "I had both knees replaced last winter.",
  "Better to have a bad round than be at work.",
  "I'm trying new balls, still getting used to them.",
  "New course, I'm not used to it yet.",
  "I'm testing this driver shaft.",
  "My rangefinder lied to me.",
  "That divot wasn't there yesterday.",
  "My caddie gave me the wrong yardage. (I don't have a caddie.)",
  "I blinked.",
  "Too much coffee this morning, hands are shaky.",
  "My watch buzzed right as I was about to putt.",
  "I was visualizing my next shot and forgot to hit this one.",
  "The tee time was too early, I'm not a morning person.",
  "I'm saving my good shots for the back nine.",
  "My lucky ball is still in the water from last week.",
  "The marshal was staring at me.",
  "I've got new grips, still breaking them in.",
  "The pin placement is cruel today.",
  "My playing partner breathed too loud.",
  "I pulled a muscle reaching for the scorecard.",
];
